# Generated by Django 5.1.7 on 2025-03-11 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_word', models.CharField(max_length=50)),
                ('max_attempts', models.IntegerField(default=6)),
                ('is_game_over', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1)),
                ('letter_states', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordle_api.game')),
            ],
        ),
    ]
