# Generated by Django 5.1.7 on 2025-03-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesses',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='wordle_api.game'),
        ),
    ]
