# Generated by Django 5.1.7 on 2025-03-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle_api', '0002_alter_guesses_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guesses_used',
            field=models.IntegerField(default=0),
        ),
    ]
