# Generated by Django 5.1.7 on 2025-03-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle_api', '0003_game_guesses_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesses',
            name='word',
            field=models.CharField(max_length=50),
        ),
    ]
